name: Build iOS (Flutter)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ridely

      - name: Build iOS app
        run: flutter build ios --release --no-codesign
        working-directory: ridely

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: ridely/build/ios/iphoneos/Runner.app
