name: Create Flutter Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Flutter project name (e.g., ridely)'
        required: true
        default: 'ridely'

jobs:
  create-flutter-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Create Flutter project
        run: flutter create ${{ github.event.inputs.project_name }}

      - name: Add project to repository
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add ${{ github.event.inputs.project_name }}
          git commit -m "chore: create Flutter project '${{ github.event.inputs.project_name }}'"
          git push
